[2025-05-19T13:49:44.285+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_spark_modelisation_command scheduled__2025-05-18T00:00:00+00:00 [queued]>
[2025-05-19T13:49:44.296+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_spark_modelisation_command scheduled__2025-05-18T00:00:00+00:00 [queued]>
[2025-05-19T13:49:44.297+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-19T13:49:44.315+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_spark_modelisation_command> on 2025-05-18 00:00:00+00:00
[2025-05-19T13:49:44.376+0000] {standard_task_runner.py:57} INFO - Started process 1090 to run task
[2025-05-19T13:49:44.382+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_transaction_data_and_upload_to_hdfs', 'run_spark_modelisation_command', 'scheduled__2025-05-18T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp2gczjnpw']
[2025-05-19T13:49:44.387+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask run_spark_modelisation_command
[2025-05-19T13:49:44.460+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_transaction_data_and_upload_to_hdfs.run_spark_modelisation_command scheduled__2025-05-18T00:00:00+00:00 [running]> on host 10b15101584c
[2025-05-19T13:49:44.842+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_transaction_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='run_spark_modelisation_command' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-18T00:00:00+00:00'
[2025-05-19T13:49:44.845+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-19T13:49:44.847+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark-master python3 modelisation.py']
[2025-05-19T13:49:44.864+0000] {subprocess.py:86} INFO - Output:
[2025-05-19T13:49:52.469+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-19T13:49:52.470+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-19T13:49:52.893+0000] {subprocess.py:93} INFO - 25/05/19 13:49:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-19T13:49:53.800+0000] {subprocess.py:93} INFO - 25/05/19 13:49:53 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-05-19T13:50:27.883+0000] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                [Stage 7:>                                                          (0 + 1) / 1]                                                                                [Stage 31:>                                                         (0 + 1) / 1]                                                                                [Stage 37:>                                                         (0 + 1) / 1][Stage 38:>                                                         (0 + 1) / 1][Stage 38:>                 (0 + 1) / 1][Stage 39:>                 (0 + 1) / 1]                                                                                [Stage 47:>                                                         (0 + 1) / 1]                                                                                [Stage 81:>                                                         (0 + 1) / 1]25/05/19 13:50:27 ERROR Utils: Aborting task
[2025-05-19T13:50:27.885+0000] {subprocess.py:93} INFO - java.lang.IllegalStateException: Error closing the output.
[2025-05-19T13:50:27.886+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:1000)
[2025-05-19T13:50:27.887+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.csv.UnivocityGenerator.close(UnivocityGenerator.scala:124)
[2025-05-19T13:50:27.888+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter.close(CsvOutputWriter.scala:48)
[2025-05-19T13:50:27.888+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseCurrentWriter(FileFormatDataWriter.scala:64)
[2025-05-19T13:50:27.889+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:75)
[2025-05-19T13:50:27.890+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:105)
[2025-05-19T13:50:27.890+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:404)
[2025-05-19T13:50:27.891+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
[2025-05-19T13:50:27.892+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:410)
[2025-05-19T13:50:27.892+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
[2025-05-19T13:50:27.893+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-05-19T13:50:27.894+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-05-19T13:50:27.894+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-05-19T13:50:27.895+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-05-19T13:50:27.895+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-05-19T13:50:27.896+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-05-19T13:50:27.897+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-05-19T13:50:27.898+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-05-19T13:50:27.899+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-05-19T13:50:27.900+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-05-19T13:50:27.901+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-05-19T13:50:27.902+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-05-19T13:50:27.905+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-05-19T13:50:27.906+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-05-19T13:50:27.907+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-05-19T13:50:27.908+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-05-19T13:50:27.909+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19/_temporary/0/_temporary/attempt_202505191350262916411598604545723_0081_m_000000_50/part-00000-5f9ecbe5-b960-4ee3-8777-315e1fe69d3b-c000.csv (inode 20935) Holder DFSClient_NONMAPREDUCE_1628651974_19 does not have any open files.
[2025-05-19T13:50:27.910+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2898)
[2025-05-19T13:50:27.911+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSDirWriteFileOp.java:693)
[2025-05-19T13:50:27.912+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFile(FSDirWriteFileOp.java:679)
[2025-05-19T13:50:27.913+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2941)
[2025-05-19T13:50:27.913+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:947)
[2025-05-19T13:50:27.914+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:620)
[2025-05-19T13:50:27.915+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-05-19T13:50:27.917+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-05-19T13:50:27.918+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-05-19T13:50:27.919+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-05-19T13:50:27.920+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-05-19T13:50:27.921+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-05-19T13:50:27.922+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-05-19T13:50:27.923+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-05-19T13:50:27.926+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-05-19T13:50:27.928+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:27.929+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-05-19T13:50:27.930+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-05-19T13:50:27.931+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-05-19T13:50:27.932+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-05-19T13:50:27.934+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-05-19T13:50:27.937+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy37.complete(Unknown Source)
[2025-05-19T13:50:27.938+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:570)
[2025-05-19T13:50:27.939+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-19T13:50:27.940+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:27.943+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:27.944+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-05-19T13:50:27.946+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-05-19T13:50:27.947+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-05-19T13:50:27.947+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-05-19T13:50:27.948+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-05-19T13:50:27.949+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-05-19T13:50:27.950+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy38.complete(Unknown Source)
[2025-05-19T13:50:27.951+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:952)
[2025-05-19T13:50:27.952+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:909)
[2025-05-19T13:50:27.953+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:892)
[2025-05-19T13:50:27.954+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:847)
[2025-05-19T13:50:27.955+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
[2025-05-19T13:50:27.955+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
[2025-05-19T13:50:27.956+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
[2025-05-19T13:50:27.957+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
[2025-05-19T13:50:27.958+0000] {subprocess.py:93} INFO - 	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
[2025-05-19T13:50:27.959+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:996)
[2025-05-19T13:50:27.960+0000] {subprocess.py:93} INFO - 	... 25 more
[2025-05-19T13:50:27.960+0000] {subprocess.py:93} INFO - 25/05/19 13:50:27 WARN FileOutputCommitter: Could not delete hdfs://namenode:9000/user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19/_temporary/0/_temporary/attempt_202505191350262916411598604545723_0081_m_000000_50
[2025-05-19T13:50:27.961+0000] {subprocess.py:93} INFO - 25/05/19 13:50:27 ERROR FileFormatWriter: Job job_202505191350262916411598604545723_0081 aborted.
[2025-05-19T13:50:27.962+0000] {subprocess.py:93} INFO - 25/05/19 13:50:27 ERROR Executor: Exception in task 0.0 in stage 81.0 (TID 50)
[2025-05-19T13:50:27.962+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: [TASK_WRITE_FAILED] Task failed while writing rows to hdfs://namenode:9000/user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19.
[2025-05-19T13:50:27.963+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:775)
[2025-05-19T13:50:27.964+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:420)
[2025-05-19T13:50:27.965+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
[2025-05-19T13:50:27.966+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-05-19T13:50:27.967+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-05-19T13:50:27.968+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-05-19T13:50:27.969+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-05-19T13:50:27.971+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-05-19T13:50:27.973+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-05-19T13:50:27.973+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-05-19T13:50:27.974+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-05-19T13:50:27.975+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-05-19T13:50:27.976+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-05-19T13:50:27.976+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-05-19T13:50:27.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-05-19T13:50:27.983+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-05-19T13:50:27.985+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-05-19T13:50:27.986+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-05-19T13:50:27.986+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-05-19T13:50:27.987+0000] {subprocess.py:93} INFO - Caused by: java.lang.IllegalStateException: Error closing the output.
[2025-05-19T13:50:27.988+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:1000)
[2025-05-19T13:50:27.992+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.csv.UnivocityGenerator.close(UnivocityGenerator.scala:124)
[2025-05-19T13:50:27.993+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter.close(CsvOutputWriter.scala:48)
[2025-05-19T13:50:27.995+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseCurrentWriter(FileFormatDataWriter.scala:64)
[2025-05-19T13:50:27.996+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:75)
[2025-05-19T13:50:27.997+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:105)
[2025-05-19T13:50:27.998+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:404)
[2025-05-19T13:50:27.999+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
[2025-05-19T13:50:28.000+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:410)
[2025-05-19T13:50:28.000+0000] {subprocess.py:93} INFO - 	... 17 more
[2025-05-19T13:50:28.001+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19/_temporary/0/_temporary/attempt_202505191350262916411598604545723_0081_m_000000_50/part-00000-5f9ecbe5-b960-4ee3-8777-315e1fe69d3b-c000.csv (inode 20935) Holder DFSClient_NONMAPREDUCE_1628651974_19 does not have any open files.
[2025-05-19T13:50:28.002+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2898)
[2025-05-19T13:50:28.002+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSDirWriteFileOp.java:693)
[2025-05-19T13:50:28.003+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFile(FSDirWriteFileOp.java:679)
[2025-05-19T13:50:28.004+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2941)
[2025-05-19T13:50:28.006+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:947)
[2025-05-19T13:50:28.008+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:620)
[2025-05-19T13:50:28.009+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-05-19T13:50:28.011+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-05-19T13:50:28.012+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-05-19T13:50:28.013+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-05-19T13:50:28.014+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-05-19T13:50:28.015+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-05-19T13:50:28.016+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-05-19T13:50:28.017+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-05-19T13:50:28.018+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-05-19T13:50:28.019+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.019+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-05-19T13:50:28.020+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-05-19T13:50:28.021+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-05-19T13:50:28.022+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-05-19T13:50:28.023+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-05-19T13:50:28.024+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy37.complete(Unknown Source)
[2025-05-19T13:50:28.025+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:570)
[2025-05-19T13:50:28.026+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-19T13:50:28.027+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.028+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.029+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-05-19T13:50:28.030+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-05-19T13:50:28.030+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-05-19T13:50:28.031+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-05-19T13:50:28.031+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-05-19T13:50:28.032+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-05-19T13:50:28.033+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy38.complete(Unknown Source)
[2025-05-19T13:50:28.034+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:952)
[2025-05-19T13:50:28.034+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:909)
[2025-05-19T13:50:28.035+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:892)
[2025-05-19T13:50:28.036+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:847)
[2025-05-19T13:50:28.037+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
[2025-05-19T13:50:28.037+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
[2025-05-19T13:50:28.038+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
[2025-05-19T13:50:28.038+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
[2025-05-19T13:50:28.039+0000] {subprocess.py:93} INFO - 	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
[2025-05-19T13:50:28.040+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:996)
[2025-05-19T13:50:28.041+0000] {subprocess.py:93} INFO - 	... 25 more
[2025-05-19T13:50:28.041+0000] {subprocess.py:93} INFO - 25/05/19 13:50:27 WARN TaskSetManager: Lost task 0.0 in stage 81.0 (TID 50) (94794bbc86c2 executor driver): org.apache.spark.SparkException: [TASK_WRITE_FAILED] Task failed while writing rows to hdfs://namenode:9000/user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19.
[2025-05-19T13:50:28.042+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:775)
[2025-05-19T13:50:28.043+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:420)
[2025-05-19T13:50:28.044+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
[2025-05-19T13:50:28.044+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-05-19T13:50:28.045+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-05-19T13:50:28.046+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-05-19T13:50:28.046+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-05-19T13:50:28.047+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-05-19T13:50:28.048+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-05-19T13:50:28.048+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-05-19T13:50:28.049+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-05-19T13:50:28.050+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-05-19T13:50:28.050+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-05-19T13:50:28.051+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-05-19T13:50:28.052+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-05-19T13:50:28.052+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-05-19T13:50:28.053+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-05-19T13:50:28.054+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-05-19T13:50:28.054+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-05-19T13:50:28.055+0000] {subprocess.py:93} INFO - Caused by: java.lang.IllegalStateException: Error closing the output.
[2025-05-19T13:50:28.056+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:1000)
[2025-05-19T13:50:28.056+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.csv.UnivocityGenerator.close(UnivocityGenerator.scala:124)
[2025-05-19T13:50:28.057+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter.close(CsvOutputWriter.scala:48)
[2025-05-19T13:50:28.058+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseCurrentWriter(FileFormatDataWriter.scala:64)
[2025-05-19T13:50:28.059+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:75)
[2025-05-19T13:50:28.059+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:105)
[2025-05-19T13:50:28.060+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:404)
[2025-05-19T13:50:28.061+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
[2025-05-19T13:50:28.061+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:410)
[2025-05-19T13:50:28.062+0000] {subprocess.py:93} INFO - 	... 17 more
[2025-05-19T13:50:28.063+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19/_temporary/0/_temporary/attempt_202505191350262916411598604545723_0081_m_000000_50/part-00000-5f9ecbe5-b960-4ee3-8777-315e1fe69d3b-c000.csv (inode 20935) Holder DFSClient_NONMAPREDUCE_1628651974_19 does not have any open files.
[2025-05-19T13:50:28.064+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2898)
[2025-05-19T13:50:28.065+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSDirWriteFileOp.java:693)
[2025-05-19T13:50:28.066+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFile(FSDirWriteFileOp.java:679)
[2025-05-19T13:50:28.067+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2941)
[2025-05-19T13:50:28.068+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:947)
[2025-05-19T13:50:28.069+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:620)
[2025-05-19T13:50:28.071+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-05-19T13:50:28.072+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-05-19T13:50:28.073+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-05-19T13:50:28.073+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-05-19T13:50:28.074+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-05-19T13:50:28.075+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-05-19T13:50:28.076+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-05-19T13:50:28.077+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-05-19T13:50:28.077+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-05-19T13:50:28.078+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.078+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-05-19T13:50:28.079+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-05-19T13:50:28.080+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-05-19T13:50:28.081+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-05-19T13:50:28.081+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-05-19T13:50:28.082+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy37.complete(Unknown Source)
[2025-05-19T13:50:28.083+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:570)
[2025-05-19T13:50:28.083+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-19T13:50:28.084+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.085+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.086+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-05-19T13:50:28.087+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-05-19T13:50:28.087+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-05-19T13:50:28.088+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-05-19T13:50:28.089+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-05-19T13:50:28.090+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-05-19T13:50:28.091+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy38.complete(Unknown Source)
[2025-05-19T13:50:28.092+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:952)
[2025-05-19T13:50:28.094+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:909)
[2025-05-19T13:50:28.094+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:892)
[2025-05-19T13:50:28.095+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:847)
[2025-05-19T13:50:28.096+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
[2025-05-19T13:50:28.097+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
[2025-05-19T13:50:28.098+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
[2025-05-19T13:50:28.098+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
[2025-05-19T13:50:28.099+0000] {subprocess.py:93} INFO - 	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
[2025-05-19T13:50:28.099+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:996)
[2025-05-19T13:50:28.100+0000] {subprocess.py:93} INFO - 	... 25 more
[2025-05-19T13:50:28.101+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.101+0000] {subprocess.py:93} INFO - 25/05/19 13:50:27 ERROR TaskSetManager: Task 0 in stage 81.0 failed 1 times; aborting job
[2025-05-19T13:50:28.102+0000] {subprocess.py:93} INFO - 25/05/19 13:50:27 ERROR FileFormatWriter: Aborting job 144dc765-6398-4edd-a4cb-b7b7dbd944f9.
[2025-05-19T13:50:28.103+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 81.0 failed 1 times, most recent failure: Lost task 0.0 in stage 81.0 (TID 50) (94794bbc86c2 executor driver): org.apache.spark.SparkException: [TASK_WRITE_FAILED] Task failed while writing rows to hdfs://namenode:9000/user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19.
[2025-05-19T13:50:28.103+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:775)
[2025-05-19T13:50:28.104+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:420)
[2025-05-19T13:50:28.105+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
[2025-05-19T13:50:28.105+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-05-19T13:50:28.106+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-05-19T13:50:28.107+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-05-19T13:50:28.108+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-05-19T13:50:28.109+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-05-19T13:50:28.110+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-05-19T13:50:28.111+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-05-19T13:50:28.112+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-05-19T13:50:28.113+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-05-19T13:50:28.113+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-05-19T13:50:28.114+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-05-19T13:50:28.115+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-05-19T13:50:28.116+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-05-19T13:50:28.117+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-05-19T13:50:28.117+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-05-19T13:50:28.118+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-05-19T13:50:28.118+0000] {subprocess.py:93} INFO - Caused by: java.lang.IllegalStateException: Error closing the output.
[2025-05-19T13:50:28.119+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:1000)
[2025-05-19T13:50:28.120+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.csv.UnivocityGenerator.close(UnivocityGenerator.scala:124)
[2025-05-19T13:50:28.120+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter.close(CsvOutputWriter.scala:48)
[2025-05-19T13:50:28.121+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseCurrentWriter(FileFormatDataWriter.scala:64)
[2025-05-19T13:50:28.121+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:75)
[2025-05-19T13:50:28.122+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:105)
[2025-05-19T13:50:28.123+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:404)
[2025-05-19T13:50:28.123+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
[2025-05-19T13:50:28.124+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:410)
[2025-05-19T13:50:28.125+0000] {subprocess.py:93} INFO - 	... 17 more
[2025-05-19T13:50:28.125+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19/_temporary/0/_temporary/attempt_202505191350262916411598604545723_0081_m_000000_50/part-00000-5f9ecbe5-b960-4ee3-8777-315e1fe69d3b-c000.csv (inode 20935) Holder DFSClient_NONMAPREDUCE_1628651974_19 does not have any open files.
[2025-05-19T13:50:28.126+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2898)
[2025-05-19T13:50:28.126+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSDirWriteFileOp.java:693)
[2025-05-19T13:50:28.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFile(FSDirWriteFileOp.java:679)
[2025-05-19T13:50:28.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2941)
[2025-05-19T13:50:28.128+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:947)
[2025-05-19T13:50:28.129+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:620)
[2025-05-19T13:50:28.129+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-05-19T13:50:28.130+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-05-19T13:50:28.130+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-05-19T13:50:28.131+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-05-19T13:50:28.131+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-05-19T13:50:28.132+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-05-19T13:50:28.133+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-05-19T13:50:28.133+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-05-19T13:50:28.134+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-05-19T13:50:28.135+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.135+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-05-19T13:50:28.136+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-05-19T13:50:28.136+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-05-19T13:50:28.137+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-05-19T13:50:28.137+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-05-19T13:50:28.138+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy37.complete(Unknown Source)
[2025-05-19T13:50:28.139+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:570)
[2025-05-19T13:50:28.139+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-19T13:50:28.140+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.141+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.141+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-05-19T13:50:28.142+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-05-19T13:50:28.142+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-05-19T13:50:28.143+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-05-19T13:50:28.143+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-05-19T13:50:28.144+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-05-19T13:50:28.145+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy38.complete(Unknown Source)
[2025-05-19T13:50:28.145+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:952)
[2025-05-19T13:50:28.146+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:909)
[2025-05-19T13:50:28.147+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:892)
[2025-05-19T13:50:28.147+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:847)
[2025-05-19T13:50:28.148+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
[2025-05-19T13:50:28.148+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
[2025-05-19T13:50:28.149+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
[2025-05-19T13:50:28.150+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
[2025-05-19T13:50:28.150+0000] {subprocess.py:93} INFO - 	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
[2025-05-19T13:50:28.151+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:996)
[2025-05-19T13:50:28.151+0000] {subprocess.py:93} INFO - 	... 25 more
[2025-05-19T13:50:28.152+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.152+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-05-19T13:50:28.153+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-05-19T13:50:28.153+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-05-19T13:50:28.154+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-05-19T13:50:28.155+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-19T13:50:28.155+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-19T13:50:28.156+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-19T13:50:28.156+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-05-19T13:50:28.157+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-05-19T13:50:28.157+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-05-19T13:50:28.157+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-05-19T13:50:28.158+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-05-19T13:50:28.159+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-05-19T13:50:28.159+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-05-19T13:50:28.160+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-05-19T13:50:28.160+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-05-19T13:50:28.161+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-05-19T13:50:28.161+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-05-19T13:50:28.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeWrite$4(FileFormatWriter.scala:307)
[2025-05-19T13:50:28.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.writeAndCommit(FileFormatWriter.scala:271)
[2025-05-19T13:50:28.163+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeWrite(FileFormatWriter.scala:304)
[2025-05-19T13:50:28.164+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:190)
[2025-05-19T13:50:28.164+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:190)
[2025-05-19T13:50:28.165+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
[2025-05-19T13:50:28.165+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
[2025-05-19T13:50:28.165+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
[2025-05-19T13:50:28.166+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$executeCollect$1(AdaptiveSparkPlanExec.scala:392)
[2025-05-19T13:50:28.166+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:420)
[2025-05-19T13:50:28.167+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:392)
[2025-05-19T13:50:28.167+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2025-05-19T13:50:28.167+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-05-19T13:50:28.168+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-05-19T13:50:28.168+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-05-19T13:50:28.169+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-05-19T13:50:28.169+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-05-19T13:50:28.169+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2025-05-19T13:50:28.170+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2025-05-19T13:50:28.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2025-05-19T13:50:28.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2025-05-19T13:50:28.172+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2025-05-19T13:50:28.172+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2025-05-19T13:50:28.172+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2025-05-19T13:50:28.173+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2025-05-19T13:50:28.174+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-05-19T13:50:28.174+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-05-19T13:50:28.175+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2025-05-19T13:50:28.175+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2025-05-19T13:50:28.176+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2025-05-19T13:50:28.177+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2025-05-19T13:50:28.177+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2025-05-19T13:50:28.178+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
[2025-05-19T13:50:28.178+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2025-05-19T13:50:28.179+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2025-05-19T13:50:28.179+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:243)
[2025-05-19T13:50:28.180+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:860)
[2025-05-19T13:50:28.180+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-19T13:50:28.181+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.182+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.182+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-05-19T13:50:28.183+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-19T13:50:28.183+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-05-19T13:50:28.184+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-19T13:50:28.185+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-19T13:50:28.185+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-19T13:50:28.186+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-19T13:50:28.187+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-19T13:50:28.187+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-05-19T13:50:28.188+0000] {subprocess.py:93} INFO - Caused by: org.apache.spark.SparkException: [TASK_WRITE_FAILED] Task failed while writing rows to hdfs://namenode:9000/user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19.
[2025-05-19T13:50:28.189+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:775)
[2025-05-19T13:50:28.189+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:420)
[2025-05-19T13:50:28.190+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
[2025-05-19T13:50:28.190+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-05-19T13:50:28.191+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-05-19T13:50:28.191+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-05-19T13:50:28.192+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-05-19T13:50:28.193+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-05-19T13:50:28.193+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-05-19T13:50:28.194+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-05-19T13:50:28.194+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-05-19T13:50:28.195+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-05-19T13:50:28.196+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-05-19T13:50:28.196+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-05-19T13:50:28.197+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-05-19T13:50:28.197+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-05-19T13:50:28.198+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-05-19T13:50:28.199+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-05-19T13:50:28.199+0000] {subprocess.py:93} INFO - 	... 1 more
[2025-05-19T13:50:28.200+0000] {subprocess.py:93} INFO - Caused by: java.lang.IllegalStateException: Error closing the output.
[2025-05-19T13:50:28.201+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:1000)
[2025-05-19T13:50:28.201+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.csv.UnivocityGenerator.close(UnivocityGenerator.scala:124)
[2025-05-19T13:50:28.202+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter.close(CsvOutputWriter.scala:48)
[2025-05-19T13:50:28.202+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseCurrentWriter(FileFormatDataWriter.scala:64)
[2025-05-19T13:50:28.203+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:75)
[2025-05-19T13:50:28.204+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:105)
[2025-05-19T13:50:28.204+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:404)
[2025-05-19T13:50:28.205+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
[2025-05-19T13:50:28.205+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:410)
[2025-05-19T13:50:28.206+0000] {subprocess.py:93} INFO - 	... 17 more
[2025-05-19T13:50:28.206+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19/_temporary/0/_temporary/attempt_202505191350262916411598604545723_0081_m_000000_50/part-00000-5f9ecbe5-b960-4ee3-8777-315e1fe69d3b-c000.csv (inode 20935) Holder DFSClient_NONMAPREDUCE_1628651974_19 does not have any open files.
[2025-05-19T13:50:28.207+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2898)
[2025-05-19T13:50:28.208+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSDirWriteFileOp.java:693)
[2025-05-19T13:50:28.208+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFile(FSDirWriteFileOp.java:679)
[2025-05-19T13:50:28.209+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2941)
[2025-05-19T13:50:28.209+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:947)
[2025-05-19T13:50:28.210+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:620)
[2025-05-19T13:50:28.210+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-05-19T13:50:28.211+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-05-19T13:50:28.212+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-05-19T13:50:28.212+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-05-19T13:50:28.213+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-05-19T13:50:28.213+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-05-19T13:50:28.214+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-05-19T13:50:28.214+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-05-19T13:50:28.215+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-05-19T13:50:28.216+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.216+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-05-19T13:50:28.217+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-05-19T13:50:28.218+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-05-19T13:50:28.219+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-05-19T13:50:28.219+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-05-19T13:50:28.220+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy37.complete(Unknown Source)
[2025-05-19T13:50:28.221+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:570)
[2025-05-19T13:50:28.221+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-19T13:50:28.222+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.222+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.223+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-05-19T13:50:28.223+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-05-19T13:50:28.224+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-05-19T13:50:28.225+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-05-19T13:50:28.225+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-05-19T13:50:28.226+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-05-19T13:50:28.226+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy38.complete(Unknown Source)
[2025-05-19T13:50:28.227+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:952)
[2025-05-19T13:50:28.228+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:909)
[2025-05-19T13:50:28.228+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:892)
[2025-05-19T13:50:28.229+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:847)
[2025-05-19T13:50:28.230+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
[2025-05-19T13:50:28.230+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
[2025-05-19T13:50:28.231+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
[2025-05-19T13:50:28.232+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
[2025-05-19T13:50:28.232+0000] {subprocess.py:93} INFO - 	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
[2025-05-19T13:50:28.233+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:996)
[2025-05-19T13:50:28.234+0000] {subprocess.py:93} INFO - 	... 25 more
[2025-05-19T13:50:28.293+0000] {subprocess.py:93} INFO - Spark session created successfully!
[2025-05-19T13:50:28.294+0000] {subprocess.py:93} INFO - Data loaded successfully. Row count: 23634
[2025-05-19T13:50:28.295+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.295+0000] {subprocess.py:93} INFO - Data Quality Check:
[2025-05-19T13:50:28.296+0000] {subprocess.py:93} INFO - Null values per column:
[2025-05-19T13:50:28.297+0000] {subprocess.py:93} INFO - -RECORD 0-----------------
[2025-05-19T13:50:28.298+0000] {subprocess.py:93} INFO -  Transaction ID     | 0
[2025-05-19T13:50:28.298+0000] {subprocess.py:93} INFO -  Customer ID        | 0
[2025-05-19T13:50:28.299+0000] {subprocess.py:93} INFO -  Transaction Amount | 0
[2025-05-19T13:50:28.300+0000] {subprocess.py:93} INFO -  Transaction Date   | 0
[2025-05-19T13:50:28.302+0000] {subprocess.py:93} INFO -  Payment Method     | 0
[2025-05-19T13:50:28.304+0000] {subprocess.py:93} INFO -  Product Category   | 0
[2025-05-19T13:50:28.305+0000] {subprocess.py:93} INFO -  Quantity           | 0
[2025-05-19T13:50:28.306+0000] {subprocess.py:93} INFO -  Customer Age       | 0
[2025-05-19T13:50:28.307+0000] {subprocess.py:93} INFO -  Customer Location  | 0
[2025-05-19T13:50:28.307+0000] {subprocess.py:93} INFO -  Device Used        | 0
[2025-05-19T13:50:28.308+0000] {subprocess.py:93} INFO -  IP Address         | 0
[2025-05-19T13:50:28.309+0000] {subprocess.py:93} INFO -  Shipping Address   | 0
[2025-05-19T13:50:28.309+0000] {subprocess.py:93} INFO -  Billing Address    | 0
[2025-05-19T13:50:28.309+0000] {subprocess.py:93} INFO -  Is Fraudulent      | 0
[2025-05-19T13:50:28.310+0000] {subprocess.py:93} INFO -  Account Age Days   | 0
[2025-05-19T13:50:28.311+0000] {subprocess.py:93} INFO -  Transaction Hour   | 0
[2025-05-19T13:50:28.311+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.312+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.312+0000] {subprocess.py:93} INFO - Sample data:
[2025-05-19T13:50:28.313+0000] {subprocess.py:93} INFO - Dimensions:
[2025-05-19T13:50:28.313+0000] {subprocess.py:93} INFO - Customers: 23634
[2025-05-19T13:50:28.314+0000] {subprocess.py:93} INFO - Payment Methods: 4
[2025-05-19T13:50:28.315+0000] {subprocess.py:93} INFO - Product Categories: 5
[2025-05-19T13:50:28.315+0000] {subprocess.py:93} INFO - Devices: 3
[2025-05-19T13:50:28.316+0000] {subprocess.py:93} INFO - Time: 23609
[2025-05-19T13:50:28.316+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.317+0000] {subprocess.py:93} INFO - Sample from Fact Transactions:
[2025-05-19T13:50:28.317+0000] {subprocess.py:93} INFO - +------------------------------------+------------------------------------+------------------+--------+---------------+-----------------------------------------------------------+-----------------------------------------------------------+-------------+---------------------+-----------------+-------------------+---------+
[2025-05-19T13:50:28.318+0000] {subprocess.py:93} INFO - |Transaction_ID                      |Customer_ID                         |Transaction_Amount|Quantity|IP_Address     |Shipping Address                                           |Billing Address                                            |Is_Fraudulent|Transaction_Timestamp|Payment_Method_ID|Product_Category_ID|Device_ID|
[2025-05-19T13:50:28.319+0000] {subprocess.py:93} INFO - +------------------------------------+------------------------------------+------------------+--------+---------------+-----------------------------------------------------------+-----------------------------------------------------------+-------------+---------------------+-----------------+-------------------+---------+
[2025-05-19T13:50:28.319+0000] {subprocess.py:93} INFO - |c12e07a0-8a06-4c0d-b5cc-04f3af688570|8ca9f102-02a4-4207-ab63-484e83a1bdf0|42.32             |1       |110.87.246.85  |5399 Rachel Stravenue Suite 718\nNorth Blakeburgh, IL 78600|5399 Rachel Stravenue Suite 718\nNorth Blakeburgh, IL 78600|0            |2024-03-24 23:42:43  |2                |2                  |0        |
[2025-05-19T13:50:28.320+0000] {subprocess.py:93} INFO - |7d187603-7961-4fce-9827-9698e2b6a201|4d158416-caae-4b09-bd5b-15235deb9129|301.34            |3       |14.73.104.153  |5230 Stephanie Forge\nCollinsbury, PR 81853                |5230 Stephanie Forge\nCollinsbury, PR 81853                |0            |2024-01-22 00:53:31  |3                |2                  |2        |
[2025-05-19T13:50:28.320+0000] {subprocess.py:93} INFO - |f2c14f9d-92df-4aaf-8931-ceaf4e63ed72|ccae47b8-75c7-4f5a-aa9e-957deced2137|340.32            |5       |67.58.94.93    |195 Cole Oval\nPort Larry, IA 58422                        |4772 David Stravenue Apt. 447\nVelasquezside, KS 67650     |0            |2024-01-22 08:06:03  |0                |1                  |0        |
[2025-05-19T13:50:28.321+0000] {subprocess.py:93} INFO - |e9949bfa-194d-486b-84da-9565fca9e5ce|b04960c0-aeee-4907-b1cd-4819016adcef|95.77             |5       |202.122.126.216|7609 Cynthia Square\nWest Brenda, NV 23016                 |7609 Cynthia Square\nWest Brenda, NV 23016                 |0            |2024-01-16 20:34:53  |3                |2                  |1        |
[2025-05-19T13:50:28.321+0000] {subprocess.py:93} INFO - |7362837c-7538-434e-8731-0df713f5f26d|de9d6351-b3a7-4bc7-9a55-8f013eb66928|77.45             |5       |96.77.232.76   |2494 Robert Ramp Suite 313\nRobinsonport, AS 52039         |2494 Robert Ramp Suite 313\nRobinsonport, AS 52039         |0            |2024-01-16 15:47:23  |3                |3                  |0        |
[2025-05-19T13:50:28.322+0000] {subprocess.py:93} INFO - +------------------------------------+------------------------------------+------------------+--------+---------------+-----------------------------------------------------------+-----------------------------------------------------------+-------------+---------------------+-----------------+-------------------+---------+
[2025-05-19T13:50:28.322+0000] {subprocess.py:93} INFO - only showing top 5 rows
[2025-05-19T13:50:28.323+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.324+0000] {subprocess.py:93} INFO - Dim_Customers DataFrame:
[2025-05-19T13:50:28.324+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.325+0000] {subprocess.py:93} INFO - Dim_Payment_Methods DataFrame:
[2025-05-19T13:50:28.325+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.326+0000] {subprocess.py:93} INFO - Dim_Product_Categories DataFrame:
[2025-05-19T13:50:28.327+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.327+0000] {subprocess.py:93} INFO - Dim_Devices DataFrame:
[2025-05-19T13:50:28.328+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.328+0000] {subprocess.py:93} INFO - Dim_Time DataFrame:
[2025-05-19T13:50:28.329+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.329+0000] {subprocess.py:93} INFO - Fact_Transactions DataFrame:
[2025-05-19T13:50:28.330+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-19T13:50:28.330+0000] {subprocess.py:93} INFO -   File "/opt/spark/work-dir/modelisation.py", line 317, in <module>
[2025-05-19T13:50:28.331+0000] {subprocess.py:93} INFO -     .csv(fact_path)
[2025-05-19T13:50:28.331+0000] {subprocess.py:93} INFO -      ^^^^^^^^^^^^^^
[2025-05-19T13:50:28.332+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/pyspark/sql/readwriter.py", line 1864, in csv
[2025-05-19T13:50:28.332+0000] {subprocess.py:93} INFO -     self._jwrite.csv(path)
[2025-05-19T13:50:28.332+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-05-19T13:50:28.333+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-05-19T13:50:28.334+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-19T13:50:28.335+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^
[2025-05-19T13:50:28.335+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j.zip/py4j/protocol.py", line 326, in get_return_value
[2025-05-19T13:50:28.367+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o281.csv.
[2025-05-19T13:50:28.368+0000] {subprocess.py:93} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 81.0 failed 1 times, most recent failure: Lost task 0.0 in stage 81.0 (TID 50) (94794bbc86c2 executor driver): org.apache.spark.SparkException: [TASK_WRITE_FAILED] Task failed while writing rows to hdfs://namenode:9000/user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19.
[2025-05-19T13:50:28.368+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:775)
[2025-05-19T13:50:28.369+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:420)
[2025-05-19T13:50:28.369+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
[2025-05-19T13:50:28.370+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-05-19T13:50:28.371+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-05-19T13:50:28.371+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-05-19T13:50:28.372+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-05-19T13:50:28.373+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-05-19T13:50:28.373+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-05-19T13:50:28.374+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-05-19T13:50:28.375+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-05-19T13:50:28.375+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-05-19T13:50:28.376+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-05-19T13:50:28.377+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-05-19T13:50:28.377+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-05-19T13:50:28.378+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-05-19T13:50:28.379+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-05-19T13:50:28.379+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-05-19T13:50:28.380+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-05-19T13:50:28.380+0000] {subprocess.py:93} INFO - Caused by: java.lang.IllegalStateException: Error closing the output.
[2025-05-19T13:50:28.381+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:1000)
[2025-05-19T13:50:28.382+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.csv.UnivocityGenerator.close(UnivocityGenerator.scala:124)
[2025-05-19T13:50:28.382+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter.close(CsvOutputWriter.scala:48)
[2025-05-19T13:50:28.383+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseCurrentWriter(FileFormatDataWriter.scala:64)
[2025-05-19T13:50:28.384+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:75)
[2025-05-19T13:50:28.384+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:105)
[2025-05-19T13:50:28.385+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:404)
[2025-05-19T13:50:28.386+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
[2025-05-19T13:50:28.386+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:410)
[2025-05-19T13:50:28.387+0000] {subprocess.py:93} INFO - 	... 17 more
[2025-05-19T13:50:28.388+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19/_temporary/0/_temporary/attempt_202505191350262916411598604545723_0081_m_000000_50/part-00000-5f9ecbe5-b960-4ee3-8777-315e1fe69d3b-c000.csv (inode 20935) Holder DFSClient_NONMAPREDUCE_1628651974_19 does not have any open files.
[2025-05-19T13:50:28.388+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2898)
[2025-05-19T13:50:28.389+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSDirWriteFileOp.java:693)
[2025-05-19T13:50:28.390+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFile(FSDirWriteFileOp.java:679)
[2025-05-19T13:50:28.391+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2941)
[2025-05-19T13:50:28.391+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:947)
[2025-05-19T13:50:28.392+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:620)
[2025-05-19T13:50:28.393+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-05-19T13:50:28.394+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-05-19T13:50:28.395+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-05-19T13:50:28.395+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-05-19T13:50:28.396+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-05-19T13:50:28.397+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-05-19T13:50:28.397+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-05-19T13:50:28.398+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-05-19T13:50:28.399+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-05-19T13:50:28.400+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.400+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-05-19T13:50:28.401+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-05-19T13:50:28.401+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-05-19T13:50:28.402+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-05-19T13:50:28.403+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-05-19T13:50:28.403+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy37.complete(Unknown Source)
[2025-05-19T13:50:28.404+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:570)
[2025-05-19T13:50:28.404+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-19T13:50:28.405+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.406+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.406+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-05-19T13:50:28.407+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-05-19T13:50:28.407+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-05-19T13:50:28.408+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-05-19T13:50:28.408+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-05-19T13:50:28.409+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-05-19T13:50:28.410+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy38.complete(Unknown Source)
[2025-05-19T13:50:28.411+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:952)
[2025-05-19T13:50:28.411+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:909)
[2025-05-19T13:50:28.412+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:892)
[2025-05-19T13:50:28.413+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:847)
[2025-05-19T13:50:28.413+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
[2025-05-19T13:50:28.414+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
[2025-05-19T13:50:28.414+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
[2025-05-19T13:50:28.415+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
[2025-05-19T13:50:28.416+0000] {subprocess.py:93} INFO - 	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
[2025-05-19T13:50:28.417+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:996)
[2025-05-19T13:50:28.418+0000] {subprocess.py:93} INFO - 	... 25 more
[2025-05-19T13:50:28.419+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.419+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-05-19T13:50:28.420+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-05-19T13:50:28.421+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-05-19T13:50:28.422+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-05-19T13:50:28.422+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-19T13:50:28.423+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-19T13:50:28.424+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-19T13:50:28.424+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-05-19T13:50:28.425+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-05-19T13:50:28.426+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-05-19T13:50:28.426+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-05-19T13:50:28.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-05-19T13:50:28.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-05-19T13:50:28.428+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-05-19T13:50:28.429+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-05-19T13:50:28.429+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-05-19T13:50:28.430+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-05-19T13:50:28.431+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-05-19T13:50:28.431+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeWrite$4(FileFormatWriter.scala:307)
[2025-05-19T13:50:28.432+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.writeAndCommit(FileFormatWriter.scala:271)
[2025-05-19T13:50:28.432+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeWrite(FileFormatWriter.scala:304)
[2025-05-19T13:50:28.433+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:190)
[2025-05-19T13:50:28.434+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:190)
[2025-05-19T13:50:28.434+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
[2025-05-19T13:50:28.435+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
[2025-05-19T13:50:28.435+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
[2025-05-19T13:50:28.436+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$executeCollect$1(AdaptiveSparkPlanExec.scala:392)
[2025-05-19T13:50:28.437+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:420)
[2025-05-19T13:50:28.437+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:392)
[2025-05-19T13:50:28.438+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2025-05-19T13:50:28.438+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-05-19T13:50:28.439+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-05-19T13:50:28.439+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-05-19T13:50:28.440+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-05-19T13:50:28.440+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-05-19T13:50:28.441+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2025-05-19T13:50:28.441+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2025-05-19T13:50:28.442+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2025-05-19T13:50:28.442+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2025-05-19T13:50:28.442+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2025-05-19T13:50:28.443+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2025-05-19T13:50:28.444+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2025-05-19T13:50:28.444+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2025-05-19T13:50:28.445+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-05-19T13:50:28.445+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-05-19T13:50:28.446+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2025-05-19T13:50:28.447+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2025-05-19T13:50:28.448+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2025-05-19T13:50:28.448+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2025-05-19T13:50:28.449+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2025-05-19T13:50:28.449+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
[2025-05-19T13:50:28.450+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2025-05-19T13:50:28.451+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2025-05-19T13:50:28.451+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:243)
[2025-05-19T13:50:28.452+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:860)
[2025-05-19T13:50:28.452+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-19T13:50:28.453+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.453+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.454+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-05-19T13:50:28.454+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-19T13:50:28.455+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-05-19T13:50:28.456+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-19T13:50:28.456+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-19T13:50:28.457+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-19T13:50:28.457+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-19T13:50:28.457+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-19T13:50:28.458+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-05-19T13:50:28.458+0000] {subprocess.py:93} INFO - Caused by: org.apache.spark.SparkException: [TASK_WRITE_FAILED] Task failed while writing rows to hdfs://namenode:9000/user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19.
[2025-05-19T13:50:28.459+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:775)
[2025-05-19T13:50:28.459+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:420)
[2025-05-19T13:50:28.460+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
[2025-05-19T13:50:28.460+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-05-19T13:50:28.461+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-05-19T13:50:28.461+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-05-19T13:50:28.462+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-05-19T13:50:28.462+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-05-19T13:50:28.463+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-05-19T13:50:28.464+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-05-19T13:50:28.464+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-05-19T13:50:28.465+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-05-19T13:50:28.466+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-05-19T13:50:28.466+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-05-19T13:50:28.467+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-05-19T13:50:28.467+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-05-19T13:50:28.468+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-05-19T13:50:28.468+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-05-19T13:50:28.469+0000] {subprocess.py:93} INFO - 	... 1 more
[2025-05-19T13:50:28.469+0000] {subprocess.py:93} INFO - Caused by: java.lang.IllegalStateException: Error closing the output.
[2025-05-19T13:50:28.470+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:1000)
[2025-05-19T13:50:28.471+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.csv.UnivocityGenerator.close(UnivocityGenerator.scala:124)
[2025-05-19T13:50:28.471+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter.close(CsvOutputWriter.scala:48)
[2025-05-19T13:50:28.472+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseCurrentWriter(FileFormatDataWriter.scala:64)
[2025-05-19T13:50:28.472+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:75)
[2025-05-19T13:50:28.473+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:105)
[2025-05-19T13:50:28.474+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:404)
[2025-05-19T13:50:28.474+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
[2025-05-19T13:50:28.475+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:410)
[2025-05-19T13:50:28.475+0000] {subprocess.py:93} INFO - 	... 17 more
[2025-05-19T13:50:28.476+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/root/datalake/fact_transactions/YYYY=2025/MM=05/DD=19/_temporary/0/_temporary/attempt_202505191350262916411598604545723_0081_m_000000_50/part-00000-5f9ecbe5-b960-4ee3-8777-315e1fe69d3b-c000.csv (inode 20935) Holder DFSClient_NONMAPREDUCE_1628651974_19 does not have any open files.
[2025-05-19T13:50:28.477+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2898)
[2025-05-19T13:50:28.477+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSDirWriteFileOp.java:693)
[2025-05-19T13:50:28.478+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFile(FSDirWriteFileOp.java:679)
[2025-05-19T13:50:28.478+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2941)
[2025-05-19T13:50:28.479+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:947)
[2025-05-19T13:50:28.480+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:620)
[2025-05-19T13:50:28.480+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-05-19T13:50:28.481+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-05-19T13:50:28.482+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-05-19T13:50:28.482+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-05-19T13:50:28.483+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-05-19T13:50:28.483+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-05-19T13:50:28.484+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-05-19T13:50:28.484+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-05-19T13:50:28.485+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-05-19T13:50:28.485+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:28.486+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-05-19T13:50:28.486+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-05-19T13:50:28.487+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-05-19T13:50:28.488+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-05-19T13:50:28.488+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-05-19T13:50:28.489+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy37.complete(Unknown Source)
[2025-05-19T13:50:28.489+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:570)
[2025-05-19T13:50:28.490+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-19T13:50:28.490+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.491+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-05-19T13:50:28.492+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-05-19T13:50:28.492+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-05-19T13:50:28.493+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-05-19T13:50:28.493+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-05-19T13:50:28.494+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-05-19T13:50:28.494+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-05-19T13:50:28.495+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy38.complete(Unknown Source)
[2025-05-19T13:50:28.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:952)
[2025-05-19T13:50:28.497+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:909)
[2025-05-19T13:50:28.498+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:892)
[2025-05-19T13:50:28.498+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:847)
[2025-05-19T13:50:28.499+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
[2025-05-19T13:50:28.499+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
[2025-05-19T13:50:28.500+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
[2025-05-19T13:50:28.501+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
[2025-05-19T13:50:28.501+0000] {subprocess.py:93} INFO - 	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
[2025-05-19T13:50:28.502+0000] {subprocess.py:93} INFO - 	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:996)
[2025-05-19T13:50:28.503+0000] {subprocess.py:93} INFO - 	... 25 more
[2025-05-19T13:50:28.504+0000] {subprocess.py:93} INFO - 
[2025-05-19T13:50:29.416+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-19T13:50:29.435+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-19T13:50:29.441+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_transaction_data_and_upload_to_hdfs, task_id=run_spark_modelisation_command, execution_date=20250518T000000, start_date=20250519T134944, end_date=20250519T135029
[2025-05-19T13:50:29.469+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task run_spark_modelisation_command (Bash command failed. The command returned a non-zero exit code 1.; 1090)
[2025-05-19T13:50:29.508+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-19T13:50:29.556+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
